### ISSUE TITLE
Add to rotate screen

### ISSUE THREAD

**Issue by tiryaki92** [arafey/openevic#12]
The screen side flip function may be functional for some users. However, the + and - keys must also be replaced. Thanks

**Comment by arafey** [comment]
Turn the device off and hold + and - together for 5 seconds. It should rotate the screen. Does this work?

**Comment by tiryaki92** [comment]
yeah its good. You are great

**Comment by tiryaki92** [comment]
When can we get the version where the issues are resolved and the opening logos can be closed? Because I still use the first version because of the opening logo.

**Comment by arafey** [comment]
That's not how it works. Each issue is done one at a time because I'm only one person. Things can take a very long time to fix because I only work on this when I have free time and don't have something else I want to do.

If you need something to be done as quickly as possible, then you should submit a [pull request](https://github.com/arafey/openevic/pulls) instead of commenting.

Thanks.
