### ISSUE TITLE
Add coil resistance moving average

### ISSUE THREAD

**Issue by tiryaki92** [arafey/openevic#6]
You can add coil stabilization feature in every mode( especially vw mode)

**Comment by arafey** [comment]
By stabilization do you mean averaging the coil resistance and just using that instead of raw values? That sounds good as long as it's not jumping around too much. If the resistance is very unstable, I don't want the "averaging" to make the device suddenly pull too many amps from the battery. It may also introduce issues because the device will not be as responsive to real coil changes until the moving average has adjusted (which may happen too slowly). 

I may need to think about this one.

**Comment by tiryaki92** [comment]
I think it is a very successful feature. If 0.3 ohm coil 0.35 is read, it can be corrected manually.

**Comment by arafey** [comment]
I will add it but keep it disabled by default. If enabled, it will default to minor stabilization (for safety), but should allow you to set higher stabilization.

**Comment by tiryaki92** [comment]
yes you are great

**Comment by arafey** [comment]
Please only close issues if it's not an issue anymore, or if I resolve the issue. Since I haven't actually written the enhancements yet, it's too early to close the issue.

As soon as I implement the feature and it works, I'll close the issue for that feature. This way, you and others who may be interested in the issue will be notified that there is a new version that takes care of it.

Thanks.

**Comment by tiryaki92** [comment]
ok, as you wish. Thanks
